### ISSUE TITLE
Windows . Switch window, page flash

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#757] opened 2022-10-28 08:54 UTC
切换窗口时会闪动

https://user-images.githubusercontent.com/95004531/198546891-aa633c53-e804-442f-880d-c3cb7dbb8df9.mp4

**Comment by capdiem** [comment] 2023-03-07 03:34
Duplicate of #605

**Closed by capdiem** 2023-03-07 03:34 UTC
Labels: type/bug, hosted/server, component/Window
