### ISSUE TITLE
Autocompletes - Click "Combobox" in "Ready for more" at the bottom and error 404 is reported

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#189] opened 2021-12-31 01:44 UTC
![error](https://user-images.githubusercontent.com/95004531/147798213-31161da2-b194-40a7-bd99-f88a26b4e35c.png)

**Comment by capdiem** [comment] 2022-06-20 08:59
Duplicate of #257

**Closed by capdiem** 2022-06-20 08:59 UTC
Labels: bug, documentation, duplicate
