### ISSUE TITLE
Carousel . The example does not animate

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#687] opened 2022-10-11 02:38 UTC
Server ：Web端，移动端

切换轮播图时，动画效果会消失

https://user-images.githubusercontent.com/95004531/194984750-6be2fcff-ddbc-4e78-9817-24319d0a9764.mp4

**Comment by capdiem** [comment] 2023-03-07 03:36
Duplicate of #605

**Closed by capdiem** 2023-03-07 03:36 UTC
Labels: type/bug, hosted/server, component/Carousel
